---
abstract: 'Ubic service module for Mojolicious Hypnotoad'
author:
  - 'Alexander Karelas <karjala@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ubic-Service-Hypnotoad
requires:
  Capture::Tiny: 0.15
  File::Basename: 0
  Time::HiRes: 0
  Ubic::Result: 0
  Ubic::Service::Skeleton: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/akarelas/ubic-service-hypnotoad/issues
  homepage: https://github.com/akarelas/ubic-service-hypnotoad
  repository: https://github.com/akarelas/ubic-service-hypnotoad.git
version: 0.1
